[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
startCommand = "sh -c \"mkdir -p public/uploads/annonces public/uploads/profiles public/uploads/products public/uploads/posts && chmod -R 777 public/uploads && php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration && php -S 0.0.0.0:${PORT:-80} -t public\""

[volumes]
uploads = "/app/public/uploads"
